// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxVn7bmt5cwRz1eYCiH2wJQXcoh9FdKi0',
    appId: '1:312330443250:web:fb830a658d1c247e99b36b',
    messagingSenderId: '312330443250',
    projectId: 'ecomerce-8d610',
    authDomain: 'ecomerce-8d610.firebaseapp.com',
    databaseURL: 'https://ecomerce-8d610-default-rtdb.firebaseio.com',
    storageBucket: 'ecomerce-8d610.appspot.com',
    measurementId: 'G-4XYVFW4VZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFQe-6IgJChAAYgJ3Vg_sSromYlVPm5pg',
    appId: '1:312330443250:android:b1eaff52eef7f23099b36b',
    messagingSenderId: '312330443250',
    projectId: 'ecomerce-8d610',
    databaseURL: 'https://ecomerce-8d610-default-rtdb.firebaseio.com',
    storageBucket: 'ecomerce-8d610.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCauvpn2LXjRckrYgn50A3Vyx5WCL8TjBU',
    appId: '1:312330443250:ios:c2781e996f67026999b36b',
    messagingSenderId: '312330443250',
    projectId: 'ecomerce-8d610',
    databaseURL: 'https://ecomerce-8d610-default-rtdb.firebaseio.com',
    storageBucket: 'ecomerce-8d610.appspot.com',
    androidClientId: '312330443250-8gt2bcttb0i27ftp7tetae8mo4c26b4r.apps.googleusercontent.com',
    iosClientId: '312330443250-64b690e4mcp90kmm0hb6c74si49lcc0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomerceWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCauvpn2LXjRckrYgn50A3Vyx5WCL8TjBU',
    appId: '1:312330443250:ios:c2781e996f67026999b36b',
    messagingSenderId: '312330443250',
    projectId: 'ecomerce-8d610',
    databaseURL: 'https://ecomerce-8d610-default-rtdb.firebaseio.com',
    storageBucket: 'ecomerce-8d610.appspot.com',
    androidClientId: '312330443250-8gt2bcttb0i27ftp7tetae8mo4c26b4r.apps.googleusercontent.com',
    iosClientId: '312330443250-64b690e4mcp90kmm0hb6c74si49lcc0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomerceWeb',
  );
}
